[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval' openweathermap.org nominatim.openstreetmap.org wttr.in;" 